import {StatusBar} from 'expo-status-bar';
import {StyleSheet, Text, View} from 'react-native';
import Mainscreen from './screen/Mainscreen';

export default function App() {
    return (
  <View>
    <Text>Personal Profile</Text>
    <Text>(message)</Text>
  </View>
  const students = [
    {name: 'Liburn' , surname: 'Jahaj' , age:'14'},

 <FlatList>
  data{students}
  keyExctractor
 </FlatList>
 
      
    
  
];
            
        
    )
}s